replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: supermedicalchain/medichain
  tag: dev_01102021.2
  pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
    limits:
      cpu: 400m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  name: medichain
initBlochain: false
services:
  grpcPort: 9090
  rpcPort: 26657
  pprofPort: 8000
  httpPort: 1317
  node:
    moniker: medichain
    chainID: test-chain
  genesis:
    account: validator1
    amount: 10000000000000token,100000000000stake
    mnemonic: hotel
