replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: supermedicalchain/medichain
  tag: dev_25092021.3
  pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
    limits:
      cpu: 400m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  name: medichain
services:
  grpcPort: 9090
  rpcPort: 26657
  pprofPort: 8000
  httpPort: 1317
  node:
    moniker: test
    chainID: medichain
  genesis:
    account: validator1
    amount: 10000000000000token,1000000000000000000stake
    mnemonic: hotel sword swarm scissors desk chase illegal idea noise humble track orient spare nurse dad insect agent prison learn polar talk soccer sadness above
    address: medichain1tgvmktene2mxwe2hx2lhqakkera0yvrcey9kak
