kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.service.name }}-pvc-1
  labels:
    chart: {{ .Values.service.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
