apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: {{ .Values.service.name | quote }}
spec:
  ports:
    - name: "{{ .Values.service.name | initials }}-rpc"
      port: {{ .Values.services.rpcPort | default "26657" }}
    - name: "{{ .Values.service.name | initials }}-grpc"
      port: {{ .Values.services.grpcPort | default "9090" }}
    - name: "{{ .Values.service.name | initials }}-http"
      port: {{ .Values.services.httpPort | default "1317" }}
    - name: "{{ .Values.service.name | initials }}-pprof"
      port: {{ .Values.services.pprofPort | default "8000" }}
  selector:
    app: "{{ .Values.service.name }}-selector"
