replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: supermedicalchain/medichain
  tag: ${TAG}
  pullPolicy: Always
  resources:
    requests:
      cpu: 200m
      memory: 100Mi
    limits:
      cpu: 400m
      memory: 300Mi
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
service:
  name: medichain
initBlockchain: ${INIT_BLOCKCHAIN}
services:
  grpcPort: ${GRPC_PORT}
  rpcPort: ${RPC_PORT}
  pprofPort: ${PPROF_PORT}
  httpPort: ${HTTP_PORT}
  adminPubKey: ${ADMIN_PUB_KEY}
  node:
    moniker: ${MONIKER}
    chainID: ${CHAIN_ID}
  genesis:
    account: ${ACCOUNT}
    amount: ${AMOUNT}
    mnemonic: ${MNEMONIC}
